EWHA-LUX/ONCE-BE

src/main/java/ewha/lux/once/domain/home/controller/HomeController.java
src/main/java/ewha/lux/once/domain/home/dto/ChatDto.java
src/main/java/ewha/lux/once/domain/home/dto/homeDto.java
src/main/java/ewha/lux/once/domain/home/entity/ChatHistory.java
src/main/java/ewha/lux/once/domain/home/entity/OwnedCard.java
src/main/java/ewha/lux/once/domain/home/repository/CardRepository.java
src/main/java/ewha/lux/once/domain/home/repository/ChatHistoryRepository.java
src/main/java/ewha/lux/once/domain/home/repository/OwnedCardRepository.java
src/main/java/ewha/lux/once/domain/home/service/HomeService.java
src/main/java/ewha/lux/once/global/config/SecurityConfig.java

> resolve #8
- 챗봇 카드 추천 (gpt 연결 x)
- 홈화면 기본 정보
- 카드 결제여부 변경

[Feature] 홈화면 관련 api 구현

---

.github/workflows/gradle.yml

> resolve #14
```
push:
branches:
- main
- develop
```

[Deploy] deploy 조건에 develop브랜치 추가

---

src/main/java/ewha/lux/once/domain/user/controller/UserController.java
src/main/java/ewha/lux/once/domain/user/dto/EditUserInfoRequestDto.java
src/main/java/ewha/lux/once/domain/user/entity/Users.java
src/main/java/ewha/lux/once/domain/user/service/UserService.java
src/main/java/ewha/lux/once/global/common/ResponseCode.java

> resolve #29
- 회원 정보 수정 API 구현
- 일부 데이터만 수정 가능

[Feat] 회원 정보 수정 api 구현

---

src/main/java/ewha/lux/once/domain/card/controller/CardController.java
src/main/java/ewha/lux/once/domain/card/dto/CardGoalRequestDto.java
src/main/java/ewha/lux/once/domain/card/dto/MontlyBenefitResponseDto.java
src/main/java/ewha/lux/once/domain/card/service/CardService.java
src/main/java/ewha/lux/once/domain/user/entity/Users.java

> resolve #36
- 월별 혜택 조회 api 구현
- 목표 혜택 금액 입력 api 구현
- 월별 혜택 조회 성공 및 예외처리
- 목표 혜택 금액 입력 성공

[Feature] 월별 혜택 조회 관련 api 구현

---

src/main/java/ewha/lux/once/domain/card/entity/OwnedCard.java
src/main/java/ewha/lux/once/domain/mypage/controller/MypageController.java
src/main/java/ewha/lux/once/domain/mypage/dto/CardListResponseDto.java
src/main/java/ewha/lux/once/domain/mypage/service/MypageService.java
src/main/java/ewha/lux/once/global/common/ResponseCode.java
src/main/java/ewha/lux/once/global/repository/OwnedCardRepository.java

> resolve #37
- 카드 목록 조회 API 구현
- 주카드 해제 API 구현
- 주카드 아닌 경우 예외 처리
- 보유 카드 아닌 경우 예외 처리 
- 등록 카드 삭제 API 구현
- 보유 카드 아닌 경우 예외 처리 
- 카드 목록 조회
<p align="center">
</p>
- 주카드 해제
<p align="center">
</p>
- 주카드 아닌 경우 예외 처리
<p align="center">
</p>
- 등록 카드 삭제
<p align="center">
</p>
- 보유 카드 아닌 경우 예외 처리
<p align="center">
</p>

[Feature] 카드 관리 관련 API 구현

---

src/main/java/ewha/lux/once/domain/home/service/HomeService.java

> resolve #45
- 알림 TimeZone 변경

[Fix] 알림 TimeZone 변경

---

Dockerfile

> resolve #45
- Dockerfile 명령어 추가

[Fix] Docker timezone 설정

---

src/main/java/ewha/lux/once/global/common/ColumnEncryptor.java

> resolve #54
커넥티드 아이디가 null인경우 복호화 과정에서 NullPointerException 발생
-> null인 경우 null 반환

[Fix] 커넥티드 아이디 복호화 오류 해결

---

.github/workflows/gradle.yml
.gitignore
src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
src/main/java/ewha/lux/once/domain/card/service/crawling/DatabaseInsert.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Hana/credit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Hana/debit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Hyundai/credit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Hyundai/debit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Kookmin/credit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Kookmin/debit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Lotte/credit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Lotte/debit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Samsung/credit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Samsung/debit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Shinhan/credit.py
src/main/java/ewha/lux/once/domain/card/service/crawling/Shinhan/debit.py
src/main/java/ewha/lux/once/global/common/ResponseCode.java

[Feat] 카드 혜택 크롤링 자동화

---

src/main/java/ewha/lux/once/domain/card/entity/BenefitSummary.java
src/main/java/ewha/lux/once/domain/card/entity/Card.java
src/main/java/ewha/lux/once/domain/card/service/CardService.java
src/main/java/ewha/lux/once/domain/home/dto/BenefitDto.java
src/main/java/ewha/lux/once/domain/home/service/HomeService.java
src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
src/main/java/ewha/lux/once/global/repository/BenefitSummaryRepository.java

> resolve #57
- GPT 프롬프트 추가
- 스케줄링 시간 설정 (월요일 04:00 AM)
- 마이월렛 API 수정
- 응답 결과 `benefit_summary` 테이블에 저장

[Feature] 카드 혜택 요약 자동화 

---

src/main/java/ewha/lux/once/domain/user/dto/UserEditResponseDto.java
src/main/java/ewha/lux/once/domain/user/entity/Users.java
src/main/java/ewha/lux/once/domain/user/service/UserService.java

> resolve #29
- 회원 정보 patch 수정
- `GET /user/edit` 응답에 username 추가
- 입력 안 된 내용 null 값으로 업데이트 되는 문제 해결
<p align="center">
</p>
- 응답에 username 추가
<p align="center">
</p>

[Feature & Fix] 회원 정보 조회 API 수정

---

.github/workflows/gradle.yml
Dockerfile
docker-compose.yml
requirements.txt
src/main/java/ewha/lux/once/domain/card/controller/CardController.java
src/main/java/ewha/lux/once/domain/card/service/CardService.java
src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
src/main/resources/crawling/DatabaseInsert.py
src/main/resources/crawling/Hana/credit.py
src/main/resources/crawling/Hana/debit.py
src/main/resources/crawling/Hyundai/credit.py
src/main/resources/crawling/Hyundai/debit.py
src/main/resources/crawling/Kookmin/credit.py
src/main/resources/crawling/Kookmin/debit.py
src/main/resources/crawling/Lotte/credit.py
src/main/resources/crawling/Lotte/debit.py
src/main/resources/crawling/Samsung/credit.py
src/main/resources/crawling/Samsung/debit.py
src/main/resources/crawling/Shinhan/credit.py
src/main/resources/crawling/Shinhan/debit.py

[Fix] 크롤링 자동화 오류 수정

---

.github/workflows/gradle.yml
Dockerfile
build.gradle
docker-compose.yml
requirements.txt
src/main/java/ewha/lux/once/domain/card/controller/CardController.java
src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
src/main/resources/crawling/DatabaseInsert.py
src/main/resources/crawling/Hana/credit.py
src/main/resources/crawling/Hana/debit.py
src/main/resources/crawling/Hyundai/credit.py
src/main/resources/crawling/Hyundai/debit.py
src/main/resources/crawling/Lotte/credit.py
src/main/resources/crawling/Lotte/debit.py
src/main/resources/crawling/Samsung/credit.py
src/main/resources/crawling/Samsung/debit.py
src/main/resources/crawling/Shinhan/credit.py
src/main/resources/crawling/Shinhan/debit.py

> resolve #66
- python, pip 설치, requirements.txt
- "python" → "python3" 변경
- 전체 경로 확인
- 크롬 실행 경로 변경
- chrome_options 변경
지금까지 오류 수정한 부분 반영했어용

[Fix] 크롤링 자동화 오류 해결 1차

---

docker-compose.yml
src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
src/main/resources/crawling/DatabaseInsert.py
src/main/resources/crawling/Hana/credit.py
src/main/resources/crawling/Hana/debit.py
src/main/resources/crawling/Hyundai/credit.py
src/main/resources/crawling/Hyundai/debit.py
src/main/resources/crawling/Kookmin/credit.py
src/main/resources/crawling/Kookmin/debit.py
src/main/resources/crawling/Lotte/credit.py
src/main/resources/crawling/Lotte/debit.py
src/main/resources/crawling/Samsung/credit.py
src/main/resources/crawling/Samsung/debit.py
src/main/resources/crawling/Shinhan/credit.py
src/main/resources/crawling/Shinhan/debit.py

> resolve #66
- 도커 로그에서 크롤링 로그 출력 안 되던 문제 해결

[Fix] 크롤링 로그 출력 문제 해결 

---

.github/workflows/gradle.yml
Dockerfile
src/main/resources/crawling/Lotte/credit.py
src/main/resources/crawling/Lotte/debit.py
src/main/resources/crawling/Samsung/debit.py

> resolve #66
- 도커 Timezone 변경
- 크롤링 코드 수정
- 롯데 config.ini 사용을 위한 환경변수 설정
지금까지 수정한 부분 반영했습니다!

[Fix] 크롤링 자동화 오류 해결 2차

---

src/main/java/ewha/lux/once/domain/card/controller/CardController.java
src/main/java/ewha/lux/once/domain/card/dto/TestSummaryDto.java
src/main/java/ewha/lux/once/domain/card/dto/TestSummaryIndexDto.java
src/main/java/ewha/lux/once/domain/card/service/CardService.java
src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
src/main/java/ewha/lux/once/global/repository/CardRepository.java

> resolve #57 
- 프롬프트 body에 넣어 테스트할 수 있게 구현
- 범위로 혜택 요약할 수 있는 컨트롤러 추가

[Test] 혜택 요약 테스트 코드 추가

---

src/main/java/ewha/lux/once/domain/card/dto/MyWalletResponseDto.java
src/main/java/ewha/lux/once/domain/card/service/CardService.java

> resolve #31
- 마이월렛 조회 응답에 닉네임 추가
<p align="center">
</p>

[Feature] 마이월렛 조회 닉네임 추가

---

src/main/java/ewha/lux/once/domain/home/service/HomeService.java
src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
src/main/java/ewha/lux/once/global/common/ResponseCode.java

> resolve #41
카드 혜택 요약 정보로 카드 추천 진행
프롬프트 업데이트(json 형식 input/output)

[Feat] gpt 프롬프트 업데이트

---

src/main/java/ewha/lux/once/domain/home/dto/ChatDto.java
src/main/java/ewha/lux/once/domain/home/service/HomeService.java

> resolve #41
- 챗봇 카드 추천 API 응답에 `cardCompany` 추가
<p align="center">
</p>
프론트엔드에서 카드사명에 따라 카드 이미지 회전하려고 응답 추가했습니당~

[Feature] 카드 추천 응답 수정

---

src/main/java/ewha/lux/once/domain/card/dto/MyWalletResponseDto.java
src/main/java/ewha/lux/once/domain/card/service/CardService.java
src/main/java/ewha/lux/once/domain/home/service/HomeService.java

> resolve #81
마이웰렛에 category 분류를 추가해 아이콘을 다르게 띄우도록 한다

[Feat] 마이웰렛 카테고리 분류 추가

---

src/main/java/ewha/lux/once/domain/user/service/UserService.java

> resolve #88
비밀번호 변경 안되는 오류 해결

fix: 비밀번호 변경 오류 수정 (#88)

---

src/main/java/ewha/lux/once/domain/home/service/AnnouncementService.java
src/main/java/ewha/lux/once/domain/home/service/HomeService.java
src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
src/main/java/ewha/lux/once/global/repository/OwnedCardRepository.java

test: 임시 업데이트
